apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.proxy.name }}-configmap
  labels:
{{- toYaml .Values.proxy.labels | nindent 4 }}
data:
{{- range $k, $v := .Values.proxy.configmap }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
